---
title: "Jules Stacy's Portfolio"
author: "Jules Stacy"
date: "February 12, 2020"
output: html_document
---


# Online Data Science Program at SMU

Additional content can be accessed via the menu button in the top right

Summary:
My name is Jules Stacy and I am in the process of obtaining my Masters' Degree in Data Science from SMU. I have prior experience as a field engineer in the oil and gas sector, a startup consultant, a sales consultant for IT solutions, and most recently in a leadership capacity in retail.

I was born and live in Houston, Texas, and have gone to three Texas schools. I lived in Hobbs, New Mexico for two years while working for Halliburton, and in Seattle for a year while working as a sales manager.

----------

Education:
In Progress: Southern Methodist University
Master of Science in Data Science
  -Expected Graduation: 2021

May 2017: University of Houston
Master of Business Administration
  -Honors Graduate
  
May 2013: Texas A&M University
Bachelor of Science in Petroleum Engineering


----------

Skills:
Data Analytics
Project Management
Operations Leadership
Problem Solving

----------

Work Experience
November 2018 - November 2019: Starbucks - Shift Supervisor
  -Promoted from Barista to Shift Supervisor after a period of 6 months
  -Led customer-facing sales at the #1 busiest store in the district
  
November 2017 - July 2018: Synology - Sales Manger
  -Consulted and maintained relationships with 120 external business partners to deliver customized data storage solutions.
  -Managed a digital marketing project in 5 states to canvas 1160 business leads utilizing Salesforce.com.
  
January 2017 - May 2017: University of Houston SURE Program - Startup Consultant
  -Successfully secured funding for 3 startups established by local Houston entrepreneurs, accelerating the startup process for
their businesses.
  -Consulted on comprehensive business plans including startup budgets, revenue forecasts based on market analysis, and investment pitches.
  
June 2013 - June 2015: Halliburton - Field Engineer
  -Oversaw production teams and provided engineering for stimulation treatments priced up to $12 million.
  -Created in-depth project plans including budget estimates for more than 75 fracturing projects.
  -Mentored 4 field engineers from hire to competency in the field.
  
----------

Interests:
National and International Travel
Bodybuilding and Physical Fitness
Music and Concerts
Playing Video Games with a Longtime Friend Group
Brunch