---
title: "ABVvsIBUscatter"
author: "Jules Stacy"
date: "February 13, 2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
library(shiny)
suppressPackageStartupMessages(library(tidyverse))

#setwd(dirname(rstudioapi::getActiveDocumentContext()$path))


beer_df = read.csv("./Data/Beers.csv")

breweries_df = read.csv("./Data/Breweries.csv")

#data cleaning
colnames(breweries_df) <- c("Brewery_id", "Brewery", "City", "State")
breweries_df$State <- str_replace_all(breweries_df$State, " ", "")

#dataset merge
beer_df = merge(beer_df, breweries_df, by="Brewery_id")

#duplicate beers were found, cleaning
beer_df <- beer_df %>% distinct(Name, ABV, IBU, Style, Ounces, .keep_all=TRUE)

#removal of NA values
beer_df = beer_df %>% filter(!is.na(ABV))
beer_df = beer_df %>% filter(!is.na(IBU))

ui <- fluidPage(
  
  # App title ----
  titlePanel("Scatterplot of ABV vs IBU Ratings"),
  br(),
  fluidRow(
    column(4,
      hr(),
      verbatimTextOutput('out3'),
      selectInput('in3', 'Use Ctrl and Click to select multiple states', c("All", state.abb), multiple=TRUE, selectize=FALSE)
    )
  ),
  
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      # Input: Select the random distribution type ----
      radioButtons("ptype", "Regression Line:",
                   c("Hide" = "hide",
                     "Show" = "show")),

      # br() element to introduce extra vertical spacing ----
      br(),
      
      #Input: Slider for the number of bins ----

    ),# end sidebarPanel
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      plotOutput( "plot")
      
    ) ) ) # end main, sidebarLayout, fluid page

# Define server logic required to draw a histogram ----
server <- function(input, output) {
  
  
  
  # Histogram of the Old Faithful Geyser Data ----
  # with requested number of bins
  # This expression that generates a histogram is wrapped in a call
  # to renderPlot to indicate that:
  #
  # 1. It is "reactive" and therefore should be automatically
  #    re-executed when inputs (input$bins) change
  # 2. Its output type is a plot
  output$plot <- renderPlot({
    #check the plot type
    if(input$ptype=="hide"){
      if(is.null(input$in3)){             #default
        #define axes
        x    <- beer_df$ABV
        y    <- beer_df$IBU
        
        #build plot
        plot(x, y, col = "#75AADB",
          xlab = "ABV",
          ylab = "IBU",
          main = "Scatter Plot of beer ABV vs IBU ratings")

      }else if(input$in3 == "All"){       #all states
        #define axes
        x    <- beer_df$ABV
        y    <- beer_df$IBU
        
        #build plot
        plot(x, y, col = "#75AADB",
          xlab = "ABV",
          ylab = "IBU",
          main = "Scatter Plot of beer ABV vs IBU ratings")
        
      }else{                              #states selected
        #define axes and select rows from states list
        beer_temp = beer_df %>% filter(beer_df$State %in% input$in3)
        x    <- beer_temp$ABV
        y    <- beer_temp$IBU
        
        
        #build plot
        plot(x, y, col = "#75AADB",
          xlab = "ABV",
          ylab = "IBU",
          main = "Scatter Plot of beer ABV vs IBU ratings")
      }
    }else{ #fit a linear regression line
      if(is.null(input$in3)){               #default
        #define axes
        x    <- beer_df$ABV
        y    <- beer_df$IBU
        
        #build linear regression data
        fit <- lm(y~x)
        xm <- seq(from=min(x), to=max(x), length=100)
        ym <- predict.lm(fit, newdata=list(x=xm))
        
        #build plot
        plot(x, y, col = "#75AADB",
          xlab = "ABV",
          ylab = "IBU",
          main = "Scatter Plot of beer ABV vs IBU ratings")
        lines(xm, ym, col=2)
        
      } else if(input$in3 == "All") {       #all states selected
        #define axes
        x    <- beer_df$ABV
        y    <- beer_df$IBU
        
        #build linear regression data
        fit <- lm(y~x)
        xm <- seq(from=min(x), to=max(x), length=100)
        ym <- predict.lm(fit, newdata=list(x=xm))
        
        #build plot
        plot(x, y, col = "#75AADB",
          xlab = "ABV",
          ylab = "IBU",
          main = "Scatter Plot of beer ABV vs IBU ratings")
        lines(xm, ym, col=2)
        
      } else{                               #specific states selected
        #define axes and select rows from states list
        beer_temp = beer_df %>% filter(beer_df$State %in% input$in3)
        x    <- beer_temp$ABV
        y    <- beer_temp$IBU
        
        #build linear regression data
        fit <- lm(y~x)
        xm <- seq(from=min(x), to=max(x), length=100)
        ym <- predict.lm(fit, newdata=list(x=xm))
        
        #build plot
        plot(x, y, col = "#75AADB",
          xlab = "ABV",
          ylab = "IBU",
          main = "Scatter Plot of beer ABV vs IBU ratings")
        lines(xm, ym, col=2)
      }

      
    }
 
  })
  
}

shinyApp(ui, server)



```