---
title: "IBUhist"
author: "Jules Stacy"
date: "February 13, 2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
library(shiny)
library(tidyverse)


beer_df = read.csv("Beers.csv")
beer_df = beer_df %>% filter(!is.na(IBU))


ui <- fluidPage(
  
  # App title ----
  titlePanel("Histogram of Beer IBU Ratings"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      # Input: Select the random distribution type ----
      radioButtons("ptype", "Plot type:",
                   c("Histogram" = "hist",
                     "Box Plot" = "box")),

      # br() element to introduce extra vertical spacing ----
      br(),
      
      #Input: Slider for the number of bins ----
      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)
    ),# end sidebarPanel
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      plotOutput( "plot")
      
    ) ) ) # end main, sidebarLayout, fluid page

# Define server logic required to draw a histogram ----
server <- function(input, output) {
  
  
  
  # Histogram of the Old Faithful Geyser Data ----
  # with requested number of bins
  # This expression that generates a histogram is wrapped in a call
  # to renderPlot to indicate that:
  #
  # 1. It is "reactive" and therefore should be automatically
  #    re-executed when inputs (input$bins) change
  # 2. Its output type is a plot
  output$plot <- renderPlot({
    
    if(input$ptype=="hist"){
    
    x    <- beer_df$IBU
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    
    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "IBU",
         main = "Histogram of beer IBU ratings")
    }else{
    x    <- beer_df$IBU
    boxplot(x, main="IBU of Beers", ylab="IBU")
      
    }
 
  })
  
}

shinyApp(ui, server)



```